name: CI/CD Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout Code
        uses: actions/checkout@v3

     
      - name: Deploy on Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd ~/repos/plotter
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
